export const CountryList = ['África do Sul','Albânia','Alemanha','Andorra',
'Angola','Anguilla','Antigua','Arábia Saudita','Argentina','Armênia','Aruba',
'Austrália','Áustria','Azerbaijão','Bahamas','Bahrein','Bangladesh','Barbados',
'Bélgica','Benin','Bermudas','Botsuana','Brasil','Brunei','Bulgária','Burkina Fasso',
'Butão','Cabo Verde','Camarões','Camboja','Canadá','Cazaquistão','Chade','Chile',
'China','Cidade do Vaticano','Colômbia','Congo','Coréia do Sul','Costa do Marfim',
'Costa Rica','Croácia','Dinamarca','Djibuti','Dominica','EUA','Egito','El Salvador',
'Emirados Árabes','Equador','Eritréia','Escócia','Eslováquia','Eslovênia','Espanha',
'Estônia','Etiópia','Fiji','Filipinas','Finlândia','França','Gabão','Gâmbia','Gana',
'Geórgia','Gibraltar','Granada','Grécia','Guadalupe','Guam','Guatemala','Guiana','Guiana Francesa',
'Guiné - bissau','Haiti','Holanda','Honduras','Hong Kong','Hungria','Iêmen','Ilhas Cayman',
'Ilhas Cook','Ilhas Curaçao','Ilhas Marshall','Ilhas Turks & Caicos','Ilhas Virgens',
,'Ilhas Wallis e Futuna','Índia','Indonésia','Inglaterra','Irlanda','Islândia','Israel',
'Itália','Jamaica','Japão','Jordânia','Kuwait','Latvia','Líbano','Liechtenstein','Lituânia',
'Luxemburgo','Macau','Macedônia','Madagascar','Malásia','Malaui','Mali','Malta','Marrocos',
'Martinica','Mauritânia','Mauritius','México','Moldova','Mônaco','Montserrat','Nepal','Nicarágua',
'Niger','Nigéria','Noruega','NovaCaledônia','Nova Zelândia','Omã','Palau','Panamá','Papua - novaGuiné',
'Paquistão','Peru','Polinésia Francesa','Polônia','PortoRico','Portugal','Qatar','Quênia','Republica Dominicana','Republica Tcheca',
'Reunion','Romênia','Ruanda','Rússia','Saipan','Samoa Americana','Senegal','Serra Leone','Seychelles','Singapura','Síria','Sri Lanka',
'St.Kitts & Nevis','St.Lúcia','St.Vincent','Sudão','Suécia','Suiça','Suriname','Tailândia','Taiwan',
'Tanzânia','Togo','Trinidad e Tobago','Tunísia','Turquia','Ucrânia','Uganda','Uruguai','Venezuela','Vietnã','Zaire','Zâmbia','Zimbábue'];